### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by Tazzios** [magnushasselquist/hqcblistmodule#7]
Thanks again for accepting my changes. I`m currently out of idea so maybe it is time for a new release. :)

Al tough I think it is wise to do some extra testing before a new release because i`m not a experience programmer. 
I will cleanup my test environment, pull the code from your github and do some extra testing this weekend.

**Comment by Tazzios** [comment]
Found an critical error which is fixed in pull https://github.com/magnushasselquist/hqcblistmodule/pull/8
For the rest it seems to work fine.

**Comment by magnushasselquist** [comment]
Again, thanks a lot!

**Comment by Tazzios** [comment]
Update did not show in joomla found out why in pull https://github.com/magnushasselquist/hqcblistmodule/pull/9

**Comment by Tazzios** [comment]
Since version 2.2 is released this issue can be closed. I have some new ideas which i will save for a next release.
